apiVersion: apps/v1
kind: Deployment
metadata:
  name: hci-app-deployment
  labels:
    app: hci-app
spec:
  selector:
    matchLabels:
      app: hci-app
  template:
    metadata:
      labels:
        app: hci-app
    spec:
      containers:
        - name: hci-app-deployment
          image: nubisub/hci:1.0.0
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: hci-app-deployment
spec:
  selector:
    app: hci-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hci-app-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hci-app-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
